env:
  - SAUCE_USERNAME=nickcmaynard-oss
addons:
  sauce_connect: true
  jwt:
  # SAUCE_ACCESS_TOKEN encrypted for Travis
  - secure: "OnM1eOOnynTqEYq3zHIXKGvEawidafw4bxZbgFw3OaHd6YjoSJgYqqPWlDJkFPiY/t8BrQ8TOY5a9zN+JzhMxACPz6y5Kexo2HsqzWOESNCQMneeozo0UDLkKTfy5VkH+T5T5zZdhdXAPYCgvzgCm2vJyC0Z+5BS4pyks64ufk8="
language: node_js
node_js:
- 6
install:
- npm install
- npm update
- npm prune
script:
- npm run ci:travis
cache:
  directories:
  - node_modules
